// Mocks generated by Mockito 5.4.6 from annotations
// in event_booking_app/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cloud_firestore/cloud_firestore.dart' as _i4;
import 'package:event_booking_app/services/database.dart' as _i2;
import 'package:event_booking_app/services/shared_pref.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DatabaseMethods].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseMethods extends _i1.Mock implements _i2.DatabaseMethods {
  MockDatabaseMethods() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addUserDetail(
    Map<String, dynamic>? userInfoMap,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addUserDetail,
          [
            userInfoMap,
            userId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserProfile(
    String? userId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [
            userId,
            data,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getUserDetail(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDetail,
          [userId],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> deleteUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addEvent(
    Map<String, dynamic>? eventInfoMap,
    String? eventId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addEvent,
          [
            eventInfoMap,
            eventId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<_i4.QuerySnapshot<Object?>> getAllEvents() => (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue: _i3.Stream<_i4.QuerySnapshot<Object?>>.empty(),
      ) as _i3.Stream<_i4.QuerySnapshot<Object?>>);

  @override
  _i3.Stream<_i4.QuerySnapshot<Object?>> getEventsByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByCategory,
          [category],
        ),
        returnValue: _i3.Stream<_i4.QuerySnapshot<Object?>>.empty(),
      ) as _i3.Stream<_i4.QuerySnapshot<Object?>>);

  @override
  _i3.Future<String> addUserBooking(
    Map<String, dynamic>? bookingInfo,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addUserBooking,
          [
            bookingInfo,
            userId,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #addUserBooking,
            [
              bookingInfo,
              userId,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Stream<_i4.QuerySnapshot<Object?>> getUserBookings(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserBookings,
          [userId],
        ),
        returnValue: _i3.Stream<_i4.QuerySnapshot<Object?>>.empty(),
      ) as _i3.Stream<_i4.QuerySnapshot<Object?>>);

  @override
  _i3.Future<String> addAdminBooking(Map<String, dynamic>? bookingInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAdminBooking,
          [bookingInfo],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #addAdminBooking,
            [bookingInfo],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Stream<_i4.QuerySnapshot<Object?>> getAllUserBookings() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllUserBookings,
          [],
        ),
        returnValue: _i3.Stream<_i4.QuerySnapshot<Object?>>.empty(),
      ) as _i3.Stream<_i4.QuerySnapshot<Object?>>);

  @override
  _i3.Stream<_i4.QuerySnapshot<Object?>> getAllTickets() => (super.noSuchMethod(
        Invocation.method(
          #getAllTickets,
          [],
        ),
        returnValue: _i3.Stream<_i4.QuerySnapshot<Object?>>.empty(),
      ) as _i3.Stream<_i4.QuerySnapshot<Object?>>);

  @override
  _i3.Stream<_i4.QuerySnapshot<Object?>> searchEvents(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEvents,
          [query],
        ),
        returnValue: _i3.Stream<_i4.QuerySnapshot<Object?>>.empty(),
      ) as _i3.Stream<_i4.QuerySnapshot<Object?>>);

  @override
  _i3.Future<_i4.DocumentSnapshot<Object?>?> getEventById(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [eventId],
        ),
        returnValue: _i3.Future<_i4.DocumentSnapshot<Object?>?>.value(),
      ) as _i3.Future<_i4.DocumentSnapshot<Object?>?>);
}

/// A class which mocks [SharedPreferenceHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferenceHelper extends _i1.Mock
    implements _i6.SharedPreferenceHelper {
  MockSharedPreferenceHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #saveUserId,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveUserName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #saveUserName,
          [name],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveUserEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #saveUserEmail,
          [email],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveUserImage(String? imageUrl) => (super.noSuchMethod(
        Invocation.method(
          #saveUserImage,
          [imageUrl],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveUserProfile({
    String? name,
    String? image,
    String? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [],
          {
            #name: name,
            #image: image,
            #role: role,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> getUserName() => (super.noSuchMethod(
        Invocation.method(
          #getUserName,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> getUserEmail() => (super.noSuchMethod(
        Invocation.method(
          #getUserEmail,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> getUserImage() => (super.noSuchMethod(
        Invocation.method(
          #getUserImage,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> getUserRole() => (super.noSuchMethod(
        Invocation.method(
          #getUserRole,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
