// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABCUjsHya7Gsav4inFCRz7RITyiRuQKnI',
    appId: '1:288536620731:web:0c9b24cc91e788ea64039e',
    messagingSenderId: '288536620731',
    projectId: 'event-booking-app-1fa34',
    authDomain: 'event-booking-app-1fa34.firebaseapp.com',
    storageBucket: 'event-booking-app-1fa34.firebasestorage.app',
    measurementId: 'G-X0EBVM16S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAof3cyPFjJDTAB6DEkv8lznevYrjmFP7I',
    appId: '1:288536620731:android:d477bd73487a1c0364039e',
    messagingSenderId: '288536620731',
    projectId: 'event-booking-app-1fa34',
    storageBucket: 'event-booking-app-1fa34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjfaoCeREepdrnlIltRwENXZ7CXYyxuh0',
    appId: '1:288536620731:ios:c89b8deca95cf9bc64039e',
    messagingSenderId: '288536620731',
    projectId: 'event-booking-app-1fa34',
    storageBucket: 'event-booking-app-1fa34.firebasestorage.app',
    androidClientId: '288536620731-7g0jeq9s3bpnr0bbkqlf0v6i1cr97t3k.apps.googleusercontent.com',
    iosClientId: '288536620731-ikl042ef0391j1b7sgtqp6scb568mt78.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjfaoCeREepdrnlIltRwENXZ7CXYyxuh0',
    appId: '1:288536620731:ios:c89b8deca95cf9bc64039e',
    messagingSenderId: '288536620731',
    projectId: 'event-booking-app-1fa34',
    storageBucket: 'event-booking-app-1fa34.firebasestorage.app',
    androidClientId: '288536620731-7g0jeq9s3bpnr0bbkqlf0v6i1cr97t3k.apps.googleusercontent.com',
    iosClientId: '288536620731-ikl042ef0391j1b7sgtqp6scb568mt78.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABCUjsHya7Gsav4inFCRz7RITyiRuQKnI',
    appId: '1:288536620731:web:18984c200a87739764039e',
    messagingSenderId: '288536620731',
    projectId: 'event-booking-app-1fa34',
    authDomain: 'event-booking-app-1fa34.firebaseapp.com',
    storageBucket: 'event-booking-app-1fa34.firebasestorage.app',
    measurementId: 'G-T2C4JXX9BW',
  );

}